version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - add_ssh_keys: 
          fingerprints: 
            - "2048 SHA256:7/rmrbp3VxJoE9SU1Mj7+GV+emNSVZy4cQw98QZNUR0 dev@console (RSA)"    
      - run: |
          gcloud version
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}    
          gsutil
      - checkout
      - run: |
          echo "great success!"
      - run: |      
          scp -r ./* dev@console.fenomen.ee:/mnt/dev/www/deployments/php-hello
