version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          gcloud version
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}    
          gsutil
      - checkout
      - store_artifacts:
          path: /index.php
          destination: index.php
      - run: |
          gsutil cp -r index.php gs://fenomen-deploytest/builds/project/sha
