version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - store_artifacts:
          path: /index.php
          destination: index.php
      - run: echo "A first hello"      
