version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - store_artifacts:
          path: /index.php
          destination: index.php
      - run: echo "A first hello"      
